name: Build & Publish Docker Image

on:
  push:
    branches: [ main ]
    tags: ['v*']

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Use your PAT to pull the base-mcp image
      - name: Log in to GHCR for pulls
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_READ }}

      # Log in with the GITHUB_TOKEN (or reuse the PAT) for pushing
      - name: Log in to GHCR for pushes
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile             # adjust if yours lives elsewhere
          push: true
          tags: |
            ghcr.io/cyreneai/discord-mcp:latest
            ghcr.io/cyreneai/discord-mcp:${{ github.sha }}
